name: 'Get JIRA tickets out of a GitHub Release'
description: 'This action will enable you to get all JIRA tickets out of a GitHub releaseÒs included PRs'
branding:
  icon: 'info'
  color: 'blue'
inputs:
  repo:
    description: 'Repository to get release from'
    required: true
    default: ''
  PAT:
    description: 'Personal access token with read access to the repositories releases'
    required: true
    default: ''
  releaseName:
    description: 'The GitHub Release's name that you want to grab the tickets from.'
    required: false
    default: 'latest'  
outputs:
  jiraTickets: # id of output
    description: 'The tickets mentioned in the description of the PRs'
runs:
  using: 'node16'
  main: 'index.js'